# Generated by Django 4.0.3 on 2022-04-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
