# Generated by Django 4.0.3 on 2022-04-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stock_alter_shortcut_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='chart_colors',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='stock',
            name='dates',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_prices',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
