# Generated by Django 4.0.3 on 2022-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_stock_current_price_alter_stock_chart_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.CharField(max_length=10),
        ),
    ]
