# Generated by Django 4.0.3 on 2022-04-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_stock_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='setstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker', models.CharField(max_length=15)),
            ],
        ),
    ]
