# Generated by Django 4.0.3 on 2022-04-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_setstock_alter_stock_chart_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('temperature', models.FloatField(blank=True, max_length=4)),
                ('condition', models.CharField(blank=True, max_length=30)),
                ('humidity', models.FloatField(blank=True, max_length=5)),
                ('pressure', models.FloatField(blank=True, max_length=8)),
                ('last_update', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
