# Generated by Django 4.0.3 on 2022-04-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
