# Generated by Django 4.0.3 on 2022-04-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_weather_humidity_alter_weather_pressure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='pressure',
            new_name='wind_speed',
        ),
    ]
