# Generated by Django 4.0.3 on 2022-04-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_pressure_weather_wind_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='time',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
