# Generated by Django 4.0.3 on 2022-04-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
